### ISSUE TITLE
npm 

### ISSUE THREAD

**Issue by wahabshah** [yeoman/doctor#19]
I tried installing yo using 
npm install -g yo
but it gave the error for not having the correct version of npm installed
I already have the latest npm installed which is 2.11.1 as shown below:-
Kindly fix it, as i cannot installed generator like generator-ko

----------------------------------------------------------------------------------------------------------------------

Your environment has been set up for using Node.js 0.12.4 (ia32) and npm.

C:\Users\kowsh>npm -version
2.11.1

C:\Users\kowsh>yo doctor

Yeoman Doctor
Running sanity checks on your system

V Global configuration file is valid
V NODE_PATH matches the npm root
V Node.js version
× npm version

Your npm version is outdated.

Upgrade to the latest version by running:
npm install -g npm

See this guide if you're having trouble upgrading:
https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

V No .bowerrc file in home directory
V No .yo-rc.json file in home directory

Found potential issues on your machine :(

-----------------------------------------------------------------------------------

**Comment by sindresorhus** [comment]
It's just a warning. You can still use `yo`. Sounds like you have multiple versions of npm installed. I would recommend you to go through this guide: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

**Comment by jcollum** [comment]
I'm using Node 4.20 LTS and getting this NPM error. But my version is the one that is bundled with the LTS: 

```
$ npm --version
2.14.7
```

This doesn't seem like it should be an error. Using the npm version that comes with the LTS version of Node seems like a sensible thing to do that shouldn't be causing an error. This should be a warning at best.

**Comment by sindresorhus** [comment]
npm@3 just didn't make the LTS release. npm@3 fixes so many issues that we would usually have to deal with. It's not an error. Just a very strong recommendation to upgrade. Pushing users to upgrade reduces the support burden for us, which means we can focus on actual features and issues instead of wasting time on endless npm install support triaging.

**Comment by jcollum** [comment]
When you put it in red text with a frowny face and a red x it sure looks like an error. You're sorta stuck with NPM 2.14.7 for a while; unfortunately I guess.

**Comment by pelo8888** [comment]
npm update -g

**Comment by razahaider** [comment]
So I just fixed this by doing :
1. /bin/bash -- login
2. sudo apt-get remove --purge node
3. sudo apt-get install nodejs
4. sudo apt-get install npm
5. npm update
6.  sudo npm install -g yo generator-kraken bower grunt-cli


Note : 1. was the most important step in my installation ;)

**Comment by mocheng** [comment]
I ran into same issue. Node version 4.4.2 and npm 2.15.0. I choose this version spec since it is LTS.

It would be appropriate to have yeoman run well with LTS version of node & npm.

**Comment by SBoudrias** [comment]
http://stackoverflow.com/questions/33487085/yodoctor-command-not-found-when-installing-yo-from-terminal

**Comment by Rathishyedla** [comment]
You need to download latest version of node.js and npm Like(node.js v 6+ and npm v 3 +). Then it's works
