### ISSUE TITLE
npm version check on windows

### ISSUE THREAD

**Issue by totof129** [yeoman/doctor#20]
npm version check on windows shall use 'npm.cmd' as argument and not only 'npm' when calling binVersionCheck function

**Comment by SBoudrias** [comment]
Mind sending a PR?

**Comment by totof129** [comment]
Hello Simon,

I'm not used to git, npm and yeoman : all I wanted to do was to quickly create a JHipster project and I was disturbed by the fact that I was told that my version was outdated ;-)
Anyway I will try to...

Regards,
Christophe
