### ISSUE TITLE
Recommend npm upgrade script on Windows npm warning

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/doctor#23]
https://github.com/felixrieseberg/npm-windows-upgrade

PR welcome :)

**Comment by SBoudrias** [comment]
For windows, we're linking to npm documentation which is presenting the npm-windows-upgrade tool. I think this is plenty sufficient.

Are we okay with closing this one considering the documentation is pretty clear about the availability of this tool? See https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

**Comment by sindresorhus** [comment]
Yeah, I think that's enough.
