### ISSUE TITLE
npm version 

### ISSUE THREAD

**Issue by sclanc** [yeoman/doctor#29]
I know that this issue is very similar to issue #19 and it seems like the internet has lots of solutions to this problem, but I have tried several and they don't seem to be working for me. I think I may have isntalled multiple versions of NPM, how can I confirm that? If that is indeed the problem, how can I purge and reinstall properly?  Here's what is going on:

 ` sudo npm install -g yo generator-kraken bower grunt-cli
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/home/sean/.npm/bin/grunt -> /home/sean/.npm/lib/node_modules/grunt-cli/bin/grunt
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
/home/sean/.npm/bin/yo -> /home/sean/.npm/lib/node_modules/yo/lib/cli.js
 
> yo@1.7.0 postinstall /home/sean/.npm/lib/node_modules/yo
> yodoctor

-
Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✖ npm version

Your npm version is outdated.

Upgrade to the latest version by running:
npm install -g npm

Found potential issues on your machine :(
 
> spawn-sync@1.0.15 postinstall /home/sean/.npm/lib/node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

/home/sean/.npm/bin/bower -> /home/sean/.npm/lib/node_modules/bower/bin/bower
grunt-cli@0.1.13 /home/sean/.npm/lib/node_modules/grunt-cli
├── nopt@1.0.10 (abbrev@1.0.7)
├── resolve@0.3.1
└── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)

yo@1.7.0 /home/sean/.npm/lib/node_modules/yo
├── titleize@1.0.0
├── cli-list@0.1.6
├── figures@1.4.0
├── async@1.5.2
├── opn@3.0.3 (object-assign@4.0.1)
├── user-home@2.0.0 (os-homedir@1.0.1)
├── humanize-string@1.0.1 (decamelize@1.1.2)
├── string-length@1.0.1 (strip-ansi@3.0.1)
├── repeating@2.0.0 (is-finite@1.0.1)
├── sort-on@1.2.2 (arrify@1.0.1, dot-prop@2.4.0)
├── root-check@1.0.0 (downgrade-root@1.1.0, sudo-block@1.2.0)
├── yeoman-character@1.1.0 (supports-color@3.1.2)
├── chalk@1.1.1 (escape-string-regexp@1.0.5, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1, ansi-styles@2.2.0)
├── yosay@1.1.0 (strip-ansi@3.0.1, ansi-regex@2.0.0, word-wrap@1.1.0, pad-component@0.0.1, minimist@1.2.0, ansi-styles@2.2.0, string-width@1.0.1, taketalk@1.0.0)
├── got@5.4.2 (lowercase-keys@1.0.0, is-stream@1.0.1, timed-out@2.0.0, is-redirect@1.0.0, is-plain-obj@1.1.0, is-retry-allowed@1.0.0, duplexer2@0.1.4, node-status-codes@1.0.0, read-all-stream@3.1.0, unzip-response@1.0.0, object-assign@4.0.1, pinkie-promise@2.0.0, url-parse-lax@1.0.0, create-error-class@2.0.1, readable-stream@2.0.5, parse-json@2.2.0)
├── update-notifier@0.6.1 (is-npm@1.0.0, latest-version@2.0.0, semver-diff@2.1.0, boxen@0.3.1)
├── package-json@2.3.1 (registry-url@3.0.3, semver@5.1.0, rc@1.1.6)
├── npm-keyword@4.2.0 (object-assign@4.0.1, pinkie-promise@2.0.0, registry-url@3.0.3)
├── cross-spawn-async@2.1.9 (lru-cache@4.0.0, which@1.2.4)
├── inquirer@0.11.4 (ansi-regex@2.0.0, strip-ansi@3.0.1, ansi-escapes@1.1.1, rx-lite@3.1.2, through@2.3.8, cli-width@1.1.1, string-width@1.0.1, readline2@1.0.1, cli-cursor@1.0.2, run-async@0.1.0)
├── configstore@1.4.0 (os-tmpdir@1.0.1, object-assign@4.0.1, graceful-fs@4.1.3, xdg-basedir@2.0.0, uuid@2.0.1, osenv@0.1.3, write-file-atomic@1.1.4, mkdirp@0.5.1)
├── fullname@2.1.0 (pify@2.3.0, pinkie-promise@2.0.0, npmconf@2.1.2)
├── meow@3.7.0 (map-obj@1.0.1, trim-newlines@1.0.0, object-assign@4.0.1, decamelize@1.1.2, camelcase-keys@2.0.0, minimist@1.2.0, redent@1.0.0, loud-rejection@1.3.0, normalize-package-data@2.3.5)
├── read-pkg-up@1.0.1 (find-up@1.1.1, read-pkg@1.1.0)
├── yeoman-doctor@2.1.0 (object-values@1.0.0, log-symbols@1.0.2, semver@5.1.0, each-async@1.1.1, bin-version-check@2.1.0, twig@0.8.8)
├── yeoman-environment@1.5.2 (log-symbols@1.0.2, escape-string-regexp@1.0.5, grouped-queue@0.3.2, text-table@0.2.0, untildify@2.1.0, diff@2.2.1, debug@2.2.0, mem-fs@1.1.2, globby@4.0.0)
├── lodash@3.10.1
└── insight@0.7.0 (object-assign@4.0.1, tough-cookie@2.2.1, lodash.debounce@3.1.1, os-name@1.0.3, inquirer@0.10.1, request@2.69.0)

generator-kraken@2.2.2 /home/sean/.npm/lib/node_modules/generator-kraken
├── debuglog@1.0.1
├── mkdirp@0.5.1 (minimist@0.0.8)
├── chalk@1.1.1 (escape-string-regexp@1.0.5, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0, ansi-styles@2.2.0)
├── underscore.string@3.3.4 (util-deprecate@1.0.2, sprintf-js@1.0.3)
├── update-notifier@0.3.2 (is-npm@1.0.0, semver-diff@2.1.0, string-length@1.0.1, latest-version@1.0.1, configstore@0.3.2)
└── yeoman-generator@0.20.3 (path-is-absolute@1.0.0, detect-conflict@1.0.0, read-chunk@1.0.1, yeoman-assert@2.1.1, yeoman-welcome@1.0.1, path-exists@1.0.0, async@1.5.2, mime@1.3.4, text-table@0.2.0, user-home@2.0.0, xdg-basedir@2.0.0, class-extend@0.1.2, dargs@4.1.0, diff@2.2.1, debug@2.2.0, nopt@3.0.6, istextorbinary@1.0.2, shelljs@0.5.3, run-async@0.1.0, through2@2.0.1, glob@5.0.15, cli-table@0.3.1, rimraf@2.5.2, findup-sync@0.2.1, yeoman-environment@1.5.2, dateformat@1.0.12, github-username@2.1.0, pretty-bytes@2.0.1, mem-fs-editor@2.2.0, cross-spawn@2.1.5, gruntfile-editor@1.1.0, sinon@1.17.3, html-wiring@1.2.0, lodash@3.10.1, inquirer@0.8.5, download@4.4.3)

bower@1.7.7 /home/sean/.npm/lib/node_modules/bower
`
Thank you very much for your help, I know that this issue probably has a simple solution, I am just having a hard time understanding what it is.

**Comment by sindresorhus** [comment]
This isn't the place to ask for npm support. 

See: https://github.com/npm/npm/wiki/Troubleshooting

**Comment by sclanc** [comment]
Thanks, sorry about that.
