### ISSUE TITLE
npm version should be 2.x

### ISSUE THREAD

**Issue by jmfrancois** [yeoman/doctor#31]
If you look at this commit https://github.com/yeoman/doctor/commit/c9c6a2370a336ab81777772d017a7bc8ef90a2b7 it means yeoman need npm3. But nodejs LTS is 4.X and this means npm is 2.X not 3.X

Should we revert partially this change and ask for node 4 and npm 2 ?

**Comment by sindresorhus** [comment]
No, that's intentional. npm@2 has lots of problems. You can easily upgrade to latest npm version with `npm i -g npm`.

**Comment by jmfrancois** [comment]
I don't understand the point. Every software has problems even npm3.
A requirement mean it can't work with npm2 or I don't think this is the case.
AKFAIK yeoman do not use internals of npm that should need npm3.

**Comment by SBoudrias** [comment]
It's not a requirement, it's a warning.

We receive hundreds of bug ticket all the time because of people hitting npm 2 bugs. This was too much work for us, so we set a warning on older npm versions.
