### ISSUE TITLE
"Your yo version is outdated"

### ISSUE THREAD

**Issue by Carglass** [yeoman/doctor#38]
When I try to install yeoman `npm install -g yo`, I receive the following status at the end of the install from yo doctor:

Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
× yo version

Your yo version is outdated.

Upgrade to the latest version by running:
npm install -g yo@latest

√ npm version

Found potential issues on your machine :(
+ yo@2.0.3
updated 1 package in 6.197s

So I tried `npm install -g yo@latest` but I end up with the same issue. It is to be noted that it was the first time I installed yo on this machine. I could not find any ressource regarding this issue, but please let me know if there is a simple solution.

Thanks,

**Comment by SBoudrias** [comment]
Is `yo` working after the install or is this failing the installation?

**Comment by Carglass** [comment]
yo is not working after the installation. I should precise that I am on a MacBook Pro on Sierra (10.12.6)

**Comment by SBoudrias** [comment]
Any chance your global npm install folder is missing from your system `PATH`?

**Comment by Carglass** [comment]
this was indeed a problem with the path. Thanks for the help!

**Comment by bvh165** [comment]
@danxfisher could you give me more details, I'm new in linux. Thank you so much

**Comment by edtorba** [comment]
Restarting CMD resolved my issue. 🤦‍♂️

**Comment by aoampov** [comment]
> Restarting CMD resolved my issue. 🤦‍♂️

Its true!!!!

**Comment by DAlSantana** [comment]
1. Run Node.Js from as Administrator

2. npm install -g yo

Be happy.
