### ISSUE TITLE
Use `yo-doctor` instead of `yodoctor`

### ISSUE THREAD

**Issue by LitoMore** [yeoman/doctor#44]
Currently the `bin` command is `yodoctor`, maybe `yo-doctor` is more readable?

**Comment by sindresorhus** [comment]
I would be in favor of that as it's more readable.

**Comment by sindresorhus** [comment]
@SBoudrias ?

**Comment by SBoudrias** [comment]
Yeah, I'm okay with this change. And it shouldn't have side effects as the command is only used on post-install script right?

We just need to make sure we don't break backward compatibility when we release it.

**Comment by LitoMore** [comment]
Sure, we just need to update the major version for this change.
